### ISSUE TITLE
Cant run on Debian Wheezy

### ISSUE THREAD

**Issue by j-4** [Dynalon/Rainy#2]
Hi Timo!

Rainy also does not start on debian wheezy. here the logs and mono version:

~/Downloads/rainy-0.1.3$ mono Rainy.exe -c settings.conf
Missing method Convert in assembly /home/jango/Downloads/rainy-0.1.3/Rainy.exe, type Microsoft.CSharp.RuntimeBinder.Binder

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
~/Downloads/rainy-0.1.3$ mono --version
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-5)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            Included Boehm (with typed GC and Parallel Mark)
~/Downloads/rainy-0.1.3$

**Comment by soldersplash** [comment]
eighthave - Did you get anywhere with the .deb packaging?

**Comment by eighthave** [comment]
it would be a bit of a pain to package as it is, since it does not run
easily as a standard UNIX daemon.  I switched to using grauphel with
owncloud, so I'm not using rainy anymore.

**Comment by soldersplash** [comment]
OK, thank you for your reply. Owncloud seems everywhere now, perhaps I should 'get with the times' :)
