### ISSUE TITLE
SQLite error: table DBUser has no column named PasswordSalt

### ISSUE THREAD

**Issue by igorsantos07** [Dynalon/Rainy#50]
When running version 0.5.0 for the first time, with SQLite backend, I receive that error when trying to create the first user via admin web interface... Is there any special thing we should do to startup the database?

**Comment by Dynalon** [comment]
you should not use any previously created database (from older rainy versions) but start over with a new db

**Comment by igorsantos07** [comment]
Great, the db file that was there must have been created by some old test with the other versions. Thanks :)
