### ISSUE TITLE
Crash on start; Rainy 0.5.0 on Mono 3.2.8

### ISSUE THREAD

**Issue by soldersplash** [Dynalon/Rainy#54]
Hi, New to Rainy, apologies in advance if this is user error!
I get the following when trying to run Rainy:
me@mypc:~$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
me@mypc:~$ cd bin/rainy-0.5.0/
me@mypc:~/bin/rainy-0.5.0$ mono Rainy.exe -c settings.conf
Missing method Convert in assembly /home/me/bin/rainy-0.5.0/Rainy.exe, type Microsoft.CSharp.RuntimeBinder.Binder

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Any suggestions?

Thanks and kind regards,
soldersplash

**Comment by soldersplash** [comment]
Some Googling and I found I need meta package mono-complete installing on debian based system to provide the missing dependencies.
`sudo apt-get mono-complete`
So not really a Rainy bug as such, more a lack of .deb package. Anyone know if their is a .deb package out there somewhere?

**Comment by Dynalon** [comment]
Installing `mono-complete` is mentioned in the documentation / install guide at: http://dynalon.github.io/Rainy/#!GETTING_STARTED.md#0._Install_requirements:
